-- Set session variables for compatibility
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
*!40101 SET NAMES utf8 */;
*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
*!40103 SET TIME_ZONE='+00:00' */;
*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Drop and create schema
DROP DATABASE IF EXISTS `PLASMABANK`;
CREATE DATABASE `PLASMABANK`;
USE `PLASMABANK`;

-- Table: BLOOD
DROP TABLE IF EXISTS `BLOOD`;
CREATE TABLE `BLOOD` (
  `plasma_bag_number` INT(11) NOT NULL,
  `blood_type` VARCHAR(10),
  `blood_amount` VARCHAR(10),
  `platelets_count` DECIMAL(5,2),
  PRIMARY KEY (`plasma_bag_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `BLOOD` VALUES (1, 'A+', '23', 2.20);

-- Table: BLOOD_COST
DROP TABLE IF EXISTS `BLOOD_COST`;
CREATE TABLE `BLOOD_COST` (
  `plasma_bag_number` INT(11) NOT NULL,
  `cost` INT(11),
  PRIMARY KEY (`plasma_bag_number`),
  FOREIGN KEY (`plasma_bag_number`) REFERENCES `BLOOD` (`plasma_bag_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `BLOOD_COST` VALUES (1, 50);

-- Table: DONORS
DROP TABLE IF EXISTS `DONORS`;
CREATE TABLE `DONORS` (
  `donor_id` INT(11) NOT NULL,
  `date_of_donation` DATE NOT NULL,
  PRIMARY KEY (`donor_id`, `date_of_donation`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `DONORS` VALUES (1, '1999-11-11');

-- Table: DONOR_INFO
DROP TABLE IF EXISTS `DONOR_INFO`;
CREATE TABLE `DONOR_INFO` (
  `donor_id` INT(11) NOT NULL,
  `fname` VARCHAR(30) NOT NULL,
  `lName` VARCHAR(30),
  `blood_type` VARCHAR(30),
  `phone_no` VARCHAR(11),
  `dOB` DATE,
  `age` INT(11),
  `sex` VARCHAR(10),
  `address` CHAR(30),
  PRIMARY KEY (`donor_id`),
  FOREIGN KEY (`donor_id`) REFERENCES `DONORS` (`donor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `DONOR_INFO` VALUES (1, 'Prateek', 'Patel', 'A+', '1234321345', '1980-12-05', 12, 'M', 'Q01 Sarojini Nagar');

-- Table: COMPANION
DROP TABLE IF EXISTS `COMPANION`;
CREATE TABLE `COMPANION` (
  `donor_id` INT(11),
  `companion_name` VARCHAR(10),
  `relationship` VARCHAR(10),
  FOREIGN KEY (`donor_id`) REFERENCES `DONORS` (`donor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Table: RECIPIENT
DROP TABLE IF EXISTS `RECIPIENT`;
CREATE TABLE `RECIPIENT` (
  `rec_id` INT(11) NOT NULL,
  `blood_type` VARCHAR(10),
  `quantity_needed` INT(11),
  `date_of_request` DATE,
  `fname` VARCHAR(10),
  `lname` VARCHAR(10),
  `dOB` DATE,
  `sex` VARCHAR(10),
  `age` INT(11),
  `address` CHAR(30),
  PRIMARY KEY (`rec_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `RECIPIENT` VALUES (1, 'A+', 23, '1999-10-10', 'Veeral', 'Agarwal', '1998-10-10', 'M', 23, 'C102, Raj Vihar, Mumbai');

-- Table: PAYMENT_TRANSACTION
DROP TABLE IF EXISTS `PAYMENT_TRANSACTION`;
CREATE TABLE `PAYMENT_TRANSACTION` (
  `rec_id` INT(11),
  `payment_amt` INT(11),
  `payment_time` VARCHAR(40),
  FOREIGN KEY (`rec_id`) REFERENCES `RECIPIENT` (`rec_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `PAYMENT_TRANSACTION` VALUES (2, 100, '06/10/2020 18:19:53');

-- Table: STAFF
DROP TABLE IF EXISTS `STAFF`;
CREATE TABLE `STAFF` (
  `emp_id` INT(11) NOT NULL,
  `fname` VARCHAR(10),
  `supervisor` VARCHAR(20),
  `address1` VARCHAR(10),
  `phone_no` BIGINT,
  `salary` INT(11),
  PRIMARY KEY (`emp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `STAFF` VALUES (1, 'Def Gef', 'Sandy', '23 A', 1234567890, 23411);

-- Table: RECIEVES
DROP TABLE IF EXISTS `RECIEVES`;
CREATE TABLE `RECIEVES` (
  `emp_id` INT(11),
  `rec_id` INT(11),
  FOREIGN KEY (`rec_id`) REFERENCES `RECIPIENT` (`rec_id`),
  FOREIGN KEY (`emp_id`) REFERENCES `STAFF` (`emp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Table: REGISTERS
DROP TABLE IF EXISTS `REGISTERS`;
CREATE TABLE `REGISTERS` (
  `donor_id` INT(11),
  `rec_id` INT(11),
  FOREIGN KEY (`rec_id`) REFERENCES `RECIPIENT` (`rec_id`),
  FOREIGN KEY (`donor_id`) REFERENCES `DONORS` (`donor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Final restore of session variables
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
